import { useState } from "react"; import { Link } from "react-router-dom"; import { Heart,MessageCircle,PenLine } from "lucide-react";
import { Button } from "@/components/ui/button"; import { CommunityAuthor } from "@/components/community/CommunityAuthor"; import { useCommunityPosts } from "@/hooks/useCommunityPosts";

export default function CommunityListPage(){const[page,setPage]=useState(0);const q=useCommunityPosts(page);return <main className="mx-auto w-full max-w-5xl px-4 py-10 sm:px-6"><header className="flex items-end justify-between gap-4 border-b border-border/50 pb-6"><div><p className="text-xs font-semibold tracking-[.2em] text-primary">COMMUNITY</p><h1 className="mt-2 text-2xl font-semibold">훈련 경험을 함께 나눠보세요</h1><p className="mt-1 text-sm text-muted-foreground">투자 결과가 아닌 판단 과정과 훈련 경험을 공유합니다.</p></div><Button asChild><Link to="/community/new"><PenLine/>글 작성</Link></Button></header>
{q.loading&&<ListSkeleton/>}{q.error&&<State text="커뮤니티를 불러오지 못했습니다." action={<Button variant="outline" size="sm" onClick={()=>void q.load()}>다시 시도</Button>}/>} {!q.loading&&!q.error&&q.data?.content.length===0&&<State text="아직 작성된 글이 없습니다." sub="첫 훈련 경험을 공유해보세요."/>}
<div className="divide-y divide-border/40">{q.data?.content.map(p=><Link key={p.id} to={`/community/${p.id}`} className="block px-1 py-5 transition-colors hover:bg-muted/15 sm:px-3"><CommunityAuthor author={p.author}/><h2 className="mt-3 text-base font-semibold">{p.title}</h2><p className="mt-1 line-clamp-2 whitespace-pre-wrap text-sm leading-6 text-muted-foreground">{p.contentPreview}</p><div className="mt-3 flex items-center gap-4 text-xs text-muted-foreground"><span className="flex items-center gap-1"><Heart className="h-3.5 w-3.5"/>{p.likeCount}</span><span className="flex items-center gap-1"><MessageCircle className="h-3.5 w-3.5"/>{p.commentCount}</span><time>{new Date(p.createdAt).toLocaleDateString("ko-KR")}</time></div></Link>)}</div>
{q.data&&q.data.totalPages>1&&<nav className="mt-6 flex justify-center gap-2"><Button variant="outline" disabled={q.data.first} onClick={()=>setPage(v=>v-1)}>이전</Button><span className="px-3 py-2 text-xs text-muted-foreground">{q.data.number+1} / {q.data.totalPages}</span><Button variant="outline" disabled={q.data.last} onClick={()=>setPage(v=>v+1)}>다음</Button></nav>}</main>}
function State({text,sub,action}:{text:string;sub?:string;action?:React.ReactNode}){return <div className="py-20 text-center"><p className="text-sm font-medium">{text}</p>{sub&&<p className="mt-1 text-xs text-muted-foreground">{sub}</p>}{action&&<div className="mt-4">{action}</div>}</div>}
function ListSkeleton(){return <div className="space-y-1 py-4" aria-label="커뮤니티 불러오는 중">{[0,1,2].map(i=><div key={i} className="h-36 animate-pulse rounded-lg bg-muted/20"/>)}</div>}
